/**
 * author : Loic France
 * created 05/31/2016
 */
Date.now||(Date.now=function(){return(new Date).getTime()});exists(window.Game)||(Game={});
Game.Manager=function(){GameManager=function(){this.running=!1;this.objects={active:[],toAdd:[],toRemove:[]};this.now=0;this.gameMap=null};GameManager.prototype.setMap=function(b){this.gameMap=b};GameManager.prototype.createMap=function(b,a,e,f){this.gameMap=new Game.Map(b,a,e);this.gameMap.setBgColor(exists(f)?f:"#000")};GameManager.prototype.getMap=function(){return this.gameMap};GameManager.prototype.getObjects=function(b){return b?this.objects.active.filter(b):this.objects.active};var d=function(b,
a){return a instanceof b};GameManager.prototype.getInstancesOf=function(b){return b?this.getObjects(d.bind(void 0,b)):this.getObjects()};GameManager.prototype.addObject=function(b){this.objects.toAdd.indexOf(-1==b)?this.objects.toAdd.push(b):console.log(Error("the object "+b+" is already being added from the game").stack)};GameManager.prototype.removeObject=function(b){this.objects.toRemove.indexOf(-1===b)?this.objects.toRemove.push(b):console.log(Error("the object "+b+" is already being removed from the game").stack)};
GameManager.prototype.clearObjects=function(){for(var b=this.objects.active.length;0<=b;b--)this.removeObject(this.objects.active[b])};GameManager.prototype.start=function(){this.running=!0;this.now=0;if(!isNull(this.gameEventsListener)&&!isNull(this.gameEventsListener.onStart))this.gameEventsListener.onStart(this);requestAnimationFrame(this.onFrame.bind(this))};GameManager.prototype.stop=function(){this.running=!1;if(!isNull(this.gameEventsListener)&&!isNull(this.gameEventsListener.onStop))this.gameEventsListener.onStop(this)};
GameManager.prototype.setGameEventsListener=function(b){this.gameEventsListener=b};GameManager.prototype.getGameEventsListener=function(){return this.gameEventsListener};GameManager.prototype.onFrame=function(b){if(this.running){if(0===this.now){this.now=b;requestAnimationFrame(this.onFrame.bind(this));return}var a,e=this.objects.active,f=this.objects.toAdd,h=this.objects.toRemove,g=h.length;if(0<g)for(;g--;)a=h.pop(),a.onDeath(this),a=e.indexOf(a),-1<a&&e.splice(a,1);h=(b-this.now)/1E3;if(0===h){console.log("error : dT=0");
return}this.now=b;if(0!==h&&.5>h){var d;b=e.filter(Game.objects.Object.collisionFilter);var k;a=g=b.length;if(0<a){for(;g--;)b[g].prepareCollision();for(g=a;g--;){a=b.pop();k=b.filter(Game.objects.Object.getCollisionLayerFilter(a.getCollisionLayers(),!0));d=k.length;if(0<d)for(;d--;)a!==k[d]&&a.canCollide(k[d])&&k[d].canCollide(a)&&a.collides(k[d])&&(a.onCollision(this,k[d]),k[d].onCollision(this,a));a.finishCollision()}}g=f.length;if(0<g)for(;g--;)e.push(f.pop());g=e.length;if(0<g)for(;g--;)e[g].onFrame(this,
h)}if(!isNull(this.gameEventsListener)&&!isNull(this.gameEventsListener.onFrame))this.gameEventsListener.onFrame(this,h)}this.gameMap&&this.gameMap.render(this,this.objects.active);requestAnimationFrame(this.onFrame.bind(this))};GameManager.prototype.showContextMenu=function(b){b=""+this.gameMap.getContextMenu();var a=this.gameMap.getObjectAt(this.gameMap.gameCoordsFromPixelCoords(position));isNull(a)||(b+=a.getContextMenu());menu.innerHtml=b+""};return GameManager}();Game.Map=function(){var d=function(b,a,e){this.context=b.getContext("2d");this.context.font="20px Verdana";this.gameWidth=a|b.width;this.gameHeight=e|b.height;this.visibleRect=new Rect(0,0,this.gameWidth,this.gameHeight)};d.prototype.setBgColor=function(b){this.context.canvas.style.background=b};d.prototype.getBg=function(){return this.context.canvas.style.background};d.prototype.setPointerPosition=function(b){this.pointerPos?this.pointerPos.set(b):this.pointerPos=b.clone();b=this.getHud();isNull(b)||
b.mouseMove(this.pointerPos)};d.prototype.getPointerPosition=function(){return this.pointerPos?this.pointerPos:Vec2.ZERO};d.prototype.useFullWindow=function(b,a){exists(b)?typeof b==TYPE_NUMBER&&(a=b,b=!0):(b=!0,a=0);this.onWindowResize&&(window.removeEventListener("resize",this.onWindowResize.bind(this,!1),!1),document.removeEventListener("fullscreenchange",this.onWindowResize.bind(this,!0),!1));if(b){typeof a!=TYPE_NUMBER&&(a=0);document.body.style.margin=0;console.log("register resize listener");
var e=this.getVisibleRect().ratio();this.onWindowResize=function(b,h){var d=window.innerWidth-a,l=Math.min(window.innerHeight-a,d/e),d=l*e;this.setSize(d,l,(window.innerWidth-d)/2,(window.innerHeight-l)/2)};window.addEventListener("resize",this.onWindowResize.bind(this,!1),!1);document.addEventListener("fullscreenchange",this.onWindowResize.bind(this,!0),!1);this.onWindowResize()}};d.prototype.setSize=function(b,a,e,f){var d=b/this.visibleRect.width(),g=a/this.visibleRect.height();this.context.canvas.width=
b;this.context.canvas.height=a;this.context.canvas.style.marginLeft=e.toString()+"px";this.context.canvas.style.marginTop=f.toString()+"px";this.context.transform(d,0,0,g,0,0);isNull(hud=this.getHud())||isNull(c=hud.getContext())||(c.width=b,c.height=a,c.canvas.style.marginLeft=e.toString()+"px",c.canvas.style.marginTop=f.toString()+"px",c.transform(d,0,0,g,0,0))};d.prototype.setVisibleRect=function(b){this.visibleRect.set(b);var a=b.width();b=b.height();this.context.transform(a?this.contexts[0].canvas.width/
a:1,0,0,b?this.contexts[0].canvas.height/b:1,0,0)};d.prototype.getVisibleRect=function(){return this.visibleRect};d.prototype.getGameRect=function(){return new Rect(0,0,this.gameWidth,this.gameHeight)};d.prototype.gameCoordsFromPixelCoords=function(b,a){var e=this.getGamePixelScaleX(),f=this.getGamePixelScaleY(),d=this.getVisibleRect().left,g=this.getVisibleRect().top;isNull(a)&&(a={});a.x=b.x*e+d;a.y=b.y*f+g;return a};d.prototype.pixelCoordsFromGameCoords=function(b,a){this.getGamePixelScaleX();
this.getGamePixelScaleY();var e=this.getVisibleRect().left,f=this.getVisibleRect().top;isNull(a)&&(a={});return a.set((b.x-e)*scale,b.y-f)};d.prototype.getGamePixelScaleX=function(){return this.getVisibleRect().width()/this.context.canvas.width};d.prototype.getGamePixelScaleY=function(){return this.getVisibleRect().height()/this.context.canvas.height};d.prototype.setHud=function(b){this.hud=b};d.prototype.createHud=function(){this.hud=new Game.hud.Hud};d.prototype.getHud=function(){return this.hud};
d.prototype.showDebug=function(b){this.debug=b};d.prototype.isDebug=function(){return this.debug};d.LAYER_NONE=-1;d.LAYER_BG1=0;d.LAYER_BG2=1;d.LAYER_BG3=2;d.LAYER_OBJ1=3;d.LAYER_OBJ2=4;d.LAYER_OBJ3=5;d.LAYER_PARTCILES=6;d.prototype.getContext=function(){return this.context};d.prototype.render=function(b,a){var e=this.getVisibleRect(),f,d=-1,g=this.context;g.clearRect(0,0,e.width(),e.height());var l=b.getGameEventsListener();l&&l.onRenderStart&&(g.save(),l.onRenderStart(b,g));for(;6>d++;){g.save();
f=a.filter(GameObject.renderLayerFilter.bind(void 0,d));var k=f.length;if(0<k)for(;k--;)f[k].isOutOfMap(e)||(f[k].render(g),this.debug&&f[k].renderDebug(g));g.restore()}this.getHud().getContext()||(g.save(),this.getHud().render(g,e),g.restore());this.showMouseOverInfos(b,a,g);l&&l.onRenderEnd&&(l.onRenderEnd(b,g),g.restore())};d.prototype.getObjectAt=function(b,a){for(var e=null,f=-1,d,g,l=b.length,k;l--;)k=b[l],isNull(k.renderMouseOver)||(d=k.getPosition()),isNull(d)||(g=Vec2.distance(d,a),(-1==
f||g<f)&&k.getRenderRect().contains(a)&&(e=k,f=g));return e};d.prototype.getContextMenu=function(){return""};d.prototype.showMouseOverInfos=function(b,a,e){e||(e=this.context);isNull(this.pointerPos)||(a=this.getObjectAt(a,this.pointerPos),isNull(a)||a.renderMouseOver(e,this.pointerPos,b,this.debug))};return d}();Game.objects={};
Game.objects.Object=function(){GameObject=function(){};GameObject.prototype.onFrame=function(b,a){this.moveOnFrame(b,a);this.accelerateOnFrame(b,a);this.rotateOnFrame(b,a);this.mustKeepInRect()&&this.maintainInRect(b.gameMap.getVisibleRect())};GameObject.prototype.moveOnFrame=function(b,a){var e=this.getSpeed();e&&!e.isZero()&&this.move(e.clone().mul(a))};GameObject.prototype.accelerateOnFrame=function(b,a){var e=this.getAcceleration();e&&!e.isZero()&&this.accelerate(e.clone().mul(a))};GameObject.prototype.rotateOnFrame=
function(b,a){var e=this.getRotationSpeed();e&&this.rotate(e*a)};GameObject.prototype.setRotationFieldEnabled=function(b){b&&!this.radians?this.radians=0:!b&&exists(this.radians)&&delete this.radians;return this};GameObject.prototype.rotate=function(b){exists(this.radians)&&(this.radians=(this.radians+b)%(2*Math.PI));this.renderer&&this.renderer.rotate(b);this.collider&&this.collider.rotate(b);return this};GameObject.prototype.setRadians=function(b){typeof b!=TYPE_NUMBER?console.log("cannot set radians to "+
b):(exists(this.radians)||this.setRotationFieldEnabled(!0),this.rotate(b-this.radians))};GameObject.prototype.getRadians=function(){return this.radians||0};GameObject.prototype.getDirection=function(){return Vec2.createFromRadians(this.getRadians())};GameObject.prototype.lookAt=function(b){exists(this.radians)||this.setRotationFieldEnabled(!0);b=Vec2.translation(this.getPosition(),b);this.setRadians(b.getAngle());return this};GameObject.prototype.setRotationSpeed=function(b){b?this.rotationSpeed=
b:this.rotationSpeed&&delete this.rotationSpeed;return this};GameObject.prototype.getRotationSpeed=function(){return this.rotationSpeed||0};GameObject.prototype.grow=function(b){this.renderer&&this.renderer.grow(b);this.collider&&this.collider.grow(b);return this};GameObject.prototype.setRenderer=function(b){this.renderer=b;return this};GameObject.prototype.getRenderer=function(){return this.renderer};GameObject.prototype.render=function(b){this.renderer&&this.renderer.render(this.getPosition(),b)};
GameObject.prototype.renderDebug=function(b){this.collider&&this.collider.render(this.getPosition(),b)};GameObject.prototype.renderMouseOver=function(b,a,e,f){!e.running&&f&&(a=this.getRect(),b.fillStyle="#fff",b.font="15px Verdana",f=this.getInformations(),a.left=a.right,a.right=e.getMap().getVisibleRect().right,b.wrapText(f.join("\n"),a,15,Gravity.LEFT,!0,!1));b.strokeStyle="#fff";(new Circle(this.getPosition(),1.1*this.getRenderRadius())).draw(b,!1,!0)};GameObject.prototype.getInformations=function(){var b=
this.getPosition(),a=this.getSpeed(),e=this.getAcceleration(),f=[];b&&f.push(["p :",b.roundedVec(4)].join(" "));a&&f.push(["s :",a.roundedVec(4)].join(" "));e&&f.push(["a :",e.roundedVec(4)].join(" "));return f};GameObject.prototype.getContextMenu=function(){return""};GameObject.prototype.getRenderLayer=function(){return Game.Map.LAYER_OBJ1};GameObject.renderLayerFilter=function(b,a){return a.getRenderLayer()==b};GameObject.prototype.setCollider=function(b){this.collider=b;return this};GameObject.prototype.getCollider=
function(){return this.collider};GameObject.prototype.canCollide=function(){return!isNull(this.getCollider())};GameObject.prototype.prepareCollision=function(){this.collision||(this.collision={});this.collision.position=this.getPosition();this.collision.collider=this.getCollider();this.collision.collider.prepareCollision(this.collision)};GameObject.prototype.finishCollision=function(){this.collision.collider.finishCollision()};GameObject.prototype.collides=function(b){return this.collision.position&&
b.collision.position&&this.collision.collider.collides(this.collision,b.collision)};GameObject.prototype.onCollision=function(b,a){};GameObject.COLLISION_LAYER=0;var d=[GameObject.COLLISION_LAYER];GameObject.prototype.getCollisionLayers=function(){return d};GameObject.prototype.isInLayer=function(b){return 0<=this.getCollisionLayers().indexOf(b)};GameObject.getCollisionLayerFilter=function(b,a){var e=b.length;return exists(e)?0<e?a?function(a){var d=e;for(a=a.getCollisionLayers();d--&&-1==a.indexOf(b[d]););
return 0<=d}:function(a){var d=e;for(a=a.getCollisionLayers();d--&&-1==a.indexOf(b[d]););return-1==d}:function(b){return!a}:a?function(a){return 0<=a.getCollisionLayers().indexOf(b)}:function(a){return-1==a.getCollisionLayers().indexOf(b)}};GameObject.collisionFilter=GameObject.getCollisionLayerFilter(-1,!1);GameObject.prototype.getRect=function(){return Rect.getUnion([this.getRenderRect(),this.getColliderRect()])};GameObject.prototype.getColliderRect=function(){var b=this.getCollider();return b?
b.getRect(this.getPosition()):Rect.createFromPoint(this.getPosition())};GameObject.prototype.getRenderRect=function(){var b=this.getRenderer();return b?b.getRect(this.getPosition()):Rect.createFromPoint(this.getPosition())};GameObject.prototype.getRadius=function(){return Math.max(this.getRenderRadius(),this.getColliderRadius())};GameObject.prototype.getRenderRadius=function(){var b=this.getRenderer();return b?b.getRadius():0};GameObject.prototype.getColliderRadius=function(){var b=this.getCollider();
return b?b.getRadius():0};GameObject.prototype.getCircle=function(){return new Circle(this.getPosition(),this.getRadius())};GameObject.prototype.getRenderCircle=function(){return new Circle(this.getPosition(),this.getRenderRadius())};GameObject.prototype.getColliderCircle=function(){return new Circle(this.getPosition(),this.getColliderRadius())};GameObject.prototype.getPosition=function(){return this.position};GameObject.prototype.getSpeed=function(){return this.speed};GameObject.prototype.getAcceleration=
function(){return this.accel};GameObject.prototype.copyPosition=function(){return this.getPosition().clone()};GameObject.prototype.copySpeed=function(){return this.getSpeed().clone()};GameObject.prototype.copyAcceleration=function(){return this.getAcceleration().clone()};GameObject.prototype.setPositionXY=function(b,a){var e=this.getPosition();e?e.setXY(b,a):this.position=new Vec2(b,a);return this};GameObject.prototype.setPosition=function(b){var a=this.getPosition();a?a.set(b):this.position=b.clone();
return this};GameObject.prototype.setSpeedXY=function(b,a){var e=this.getSpeed();e?e.setXY(b,a):this.speed=new Vec2(b,a);return this};GameObject.prototype.setSpeed=function(b){var a=this.getSpeed();a?a.set(b):this.speed=b.clone();return this};GameObject.prototype.setAccelerationXY=function(b,a){var e=this.getAcceleration();e?e.setXY(b,a):this.accel=new Vec2(b,a);return this};GameObject.prototype.setAcceleration=function(b){var a=this.getAcceleration();a?a.set(b):this.accel=b.clone();return this};
GameObject.prototype.moveXY=function(b,a){var e=this.getPosition();e&&this.setPosition(e.addXY(b,a));return this};GameObject.prototype.move=function(b){var a=this.getPosition();a&&this.setPosition(a.add(b));return this};GameObject.prototype.accelerateXY=function(b,a){var e=this.getSpeed();e&&this.setSpeed(e.addXY(b,a));return this};GameObject.prototype.accelerate=function(b){var a=this.getSpeed();a&&this.setSpeed(a.add(b));return this};GameObject.prototype.kill=function(b){b.removeObject(this)};GameObject.prototype.onDeath=
function(b){};GameObject.prototype.isOutOfMap=function(b,a,e){b=b.clone();exists(a)&&b.addMarginsXY(-a,exists(e)?-e:-a);if(a=this.getPosition()){if(b.contains(a))return 0;b.addMargin(this.getRadius());e=0;a.x<b.left?e|=1:a.x>b.right&&(e|=4);a.y<b.top?e|=2:a.y>b.bottom&&(e|=8);return e}return 0};GameObject.prototype.maintainInRect=function(b,a,e){exists(a)&&(b=b.clone().addMarginsXY(-a,exists(e)?-e:-a));var f=this.getRect();a=this.getPosition();e=this.getSpeed();var d=f.left<b.left?b.left-f.left:f.right>
b.right?b.right-f.right:0;b=f.top<b.top?b.top-f.top:f.bottom>b.bottom?b.bottom-f.bottom:0;d&&(a.x+=d,0<e.x&&0>d||0>e.x&&0<d)&&(e.x=0);b&&(a.y+=b,0<e.y&&0>b||0>e.y&&0<b)&&(e.y=0)};GameObject.prototype.mustKeepInRect=function(){return!1};GameObject.prototype.toString=function(){return["object at",this.getPosition()].join(" ")};GameObject.Static=function(b){GameObject.call(this);this.setPosition(b?b:Vec2.ZERO)};classExtend(GameObject,GameObject.Static);GameObject.Cinetic=function(b){GameObject.Static.call(this,
b);this.setSpeed(Vec2.ZERO)};classExtend(GameObject.Static,GameObject.Cinetic);GameObject.Dynamic=function(b){GameObject.Cinetic.call(this,b);this.setAcceleration(Vec2.ZERO)};classExtend(GameObject.Cinetic,GameObject.Dynamic);return GameObject}();Game.objects.renderers=function(){var d={};d.Renderer=function(){var b=function(){};b.prototype.rotate=function(a){};b.prototype.grow=function(a){};b.prototype.render=function(a,b){};b.prototype.getRadius=function(){return 0};b.prototype.getRect=function(a){return Rect.createFromPoint(a)};return b}();d.Shaped=function(){parent=d.Renderer;ShapedRenderer=function(b,a){this.shape=b.clone();this.color=a};classExtend(parent,ShapedRenderer);ShapedRenderer.prototype.fill=!0;ShapedRenderer.prototype.stroke=
!1;ShapedRenderer.prototype.rotate=function(b){this.shape.rotate(b)};ShapedRenderer.prototype.grow=function(b){this.shape.grow(b)};ShapedRenderer.prototype.getColor=function(){return this.color};ShapedRenderer.prototype.setColor=function(b){this.color=b};ShapedRenderer.prototype.setShape=function(b){this.shape=b.clone()};ShapedRenderer.prototype.getShape=function(){return this.shape};ShapedRenderer.prototype.render=function(b,a){this.fill&&(a.fillStyle=this.color);this.stroke&&(a.strokeStyle=this.color);
this.shape.moveTo(b);this.shape.draw(a,this.fill,this.stroke)};ShapedRenderer.prototype.getRect=function(b){this.shape.moveTo(b);return this.shape.getRect()};ShapedRenderer.prototype.getRadius=function(){return this.shape.getRadius()};return ShapedRenderer}();return d}();Game.objects.colliders=function(){var d={},b=function(){var a=function(){};a.prototype.rotate=function(a){};a.prototype.grow=function(a){};a.prototype.getRadius=function(){return 0};a.prototype.getRect=function(a){return Rect.createFromPoint(a)};a.prototype.collidesWhenInside=function(a){return!1};a.prototype.prepareCollision=function(a){a.rect?a.rect.setRect(this.getRect(a.position)):a.rect=this.getRect(a.position)};a.prototype.finishCollision=function(){};a.prototype.collides=function(a,b){return!1};
return a}();d.Collider=b;d.Collider.prototype=b.prototype;b=function(){parent=d.Collider;var a=function(a){this.shape=a.clone()};classExtend(parent,a);a.prototype.rotate=function(a){this.shape.rotate(a)};a.prototype.grow=function(a){this.shape.grow(a)};a.prototype.getShape=function(){return this.shape};a.prototype.setShape=function(a){this.shape=a.clone()};a.prototype.collides=function(a,b){var d=b.collider;return b.collider.shape&&b.rect.overlap(a.rect)&&this.shape.intersect(d.shape)||this.collidesWhenInside(d)&&
d.shape.contains(a.position)||d.collidesWhenInside(this)&&this.shape.contains(b.position)};a.prototype.getRect=function(a){a&&this.shape.moveTo(a);return this.shape.getRect()};a.prototype.getRadius=function(){return this.shape.getRadius()};a.prototype.render=function(a,b){b.strokeStyle="#ff0000";this.getRect(a).draw(b,!1,!0);this.shape.draw(b,!1,!0)};return a}();d.Shaped=b;d.Shaped.prototype=b.prototype;return d}();Game.objects.properties={};
Game.objects.properties.Health={isDamageable:function(d){return exists(d.receiveDamages)},applyOnClass:function(d){d.prototype.receiveDamages=function(a,b,d){if(0>=this.health)return!1;this.health-=d;0>=this.health&&this.kill(a);return!0};d.prototype.heal=function(a){this.health+=a;!isNull(this.maxHealth)&&this.health>this.maxHealth&&(this.health=this.maxHealth)};d.prototype.setHealth=function(a){this.health=a};d.prototype.getHealth=function(){return this.health};var b=override(d,"getInformations",
function(){var a=b.call(this);a.push(["health :",this.health.toPrecision(4)].join(" "));return a});d.prototype.setMaxHealth=function(a){this.maxHealth=a};d.prototype.getMaxHealth=function(){return this.maxHealth};var a=override(d,"onDeath",function(b){a.call(b);isNull(this.maxHealth)||delete this.maxHealth;delete this.health})}};
Game.objects.properties.Energy={applyOnClass:function(d){d.prototype.useEnergy=function(a){if(this.getEnergy()<a)return!1;this.setEnergy(this.getEnergy()-a);return!0};d.prototype.setMaxEnergy=function(a){this.maxEnergy=a};d.prototype.setEnergy=function(a){this.energy=a};d.prototype.recoverEnergy=function(a){if(this.isEnergyFull())return!1;this.setEnergy(this.getEnergy()+a);this.isEnergyFull()&&this.setEnergy(this.getMaxEnergy());return!0};d.prototype.isEnergyFull=function(){return this.getEnergy()>=
this.getMaxEnergy()};d.prototype.setEnergyRecoverSpeed=function(a){this.energyRecoverSpeed=a};d.prototype.getMaxEnergy=function(){return this.maxEnergy};d.prototype.getEnergy=function(){return this.energy};d.prototype.getEnergyRecoverSpeed=function(){return this.energyRecoverSpeed};var b=override(d,"onFrame",function(a,e){b.call(this,a,e);var d=this.getEnergyRecoverSpeed();d&&!this.isEnergyFull()&&this.recoverEnergy(d*e)}),a=override(d,"getInformations",function(){var b=a.call(this);b.push(["energy :",
this.energy.toPrecision(4)].join(" "));return b}),e=override(d,"onDeath",function(a){e.call(a);delete this.energy;delete this.energyRecoverSpeed;delete this.maxEnergy})}};
Game.objects.properties.Homing={getSteeringForce:function(d,b,a,e,f){return Vec2.translation(d,f).normalize().mul(b).remove(e).clampMagnitude(0,a)},applyOnClass:function(d,b,a,e){var f=override(d,"onFrame",function(a,b){if(this.getTarget){var e=this.getTarget(a);if(e){e instanceof Game.objects.Object&&(e=e.getPosition());var d=this.getPosition(),n=Vec2.translation(d,e),p=n.magnitude(),m=this.getMaxSpeed(p),q=this.getSteerForce(m,p),n=n.mul(q/p);n.add(Game.objects.properties.Homing.getSteeringForce(d,
m,q,this.getSpeed(),e)).normalize().mul(q);this.setAcceleration(n);f.call(this,a,b);this.setSpeed(this.getSpeed().clampMagnitude(0,m))}else this.setAcceleration(Vec2.ZERO),f.call(this,a,b)}else f.call(this,a,b)});isNull(e)||(d.prototype.getTarget=e);isNull(b)?d.prototype.getMaxSpeed=function(a){return 200}:d.prototype.getMaxSpeed=function(a){return b};isNull(a)?d.prototype.getSteerForce=function(a,b){return 100}:d.prototype.getSteerForce=function(b,e){return a}},applyOnObject:function(d,b,a,e){var f=
d.onFrame;d.onFrame=function(d,g){var l=e(d);if(isNull(l))this.setAcceleration(Vec2.ZERO);else{console.log(l);l instanceof Game.objects.Object&&(l=l.getPosition());var k=this.getPosition(),n=Vec2.translation(k,l).normalize().mul(steer);n.add(Homing.getSteeringForce(k,this.getSpeed(),b,a,this.getSpeed(),l));this.setAcceleration(n)}f.call(this,d,g)}}};
Game.objects.properties.LifeTime={applyOnClass:function(d){var b=d.prototype.onFrame;d.prototype.onFrame=function(a,e){0>=this.lifeTime&&this.kill(a);b.call(this,a,e);this.lifeTime&&(this.lifeTime-=e)};var a=override(d,"getInformations",function(){if(isNull(this.lifeTime))return a.call(this);var b=a.call(this);b.push(["lifeTime :",this.lifeTime.toPrecision(4)].join(" "));return b}),e=override(d,"onDeath",function(a){e.call(a);delete this.lifeTime})},applyOnObject:function(d){var b=d.onFrame;d.onFrame=
function(a,e){0>=this.lifeTime&&this.kill(a);b.apply(this,arguments);exists(this.lifeTime)&&(this.lifeTime-=e)};d.onDeath=function(a){exists(this.lifeTime)&&delete this.LifeTime}}};
Game.objects.properties.Tag=function(){var d=function(b,a){return a.hasTag&&a.hasTag(b)};return{canHaveTag:function(b){return b.hasTag},hasTag:function(b,a){return b.hasTag&&b.hasTag(a)},getAllObjectsWithTag:function(b,a){return isNull(a)?b.getObjects(canHaveTag):b.getObjects(d.bind(void 0,a))},applyOnClass:function(b){b.prototype.addTag=function(a){this.tags||(this.tags=[]);this.tags.push(a)};b.prototype.hasTag=function(a){return!isNull(this.tags)&&-1!==this.tags.indexOf(a)};b.prototype.getTags=
function(){return this.tags};b.prototype.isTagged=function(){return this.tags?!0:!1};var a=override(b,"getInformations",function(){var b=this.getTags();return!isNull(b)&&0<b.length?(b=a.call(this),b.push(["tags :",this.tags.join(", ")].join(" ")),b):a.call(this)}),e=override(b,"onDeath",function(a){e.call(a);exists(this.tags)&&delete this.tags})}}}();Game.objects.Follower=function(){var d=Game.objects.Object.Dynamic,b=function(a,b,f,h){d.call(this,a);this.maxSpeed=exists(f)?f:100;this.steerForce=exists(h)?h:f;this.setTarget(b)};classExtend(d,b);Game.objects.properties.Homing.applyOnClass(b);b.prototype.onDeath=function(a){var b=a.getGameEventsListener();if(b)b.onObjectDestroyed(a,this)};b.prototype.getMaxSpeed=function(){return this.maxSpeed};b.prototype.getSteerForce=function(){return this.steerForce};b.prototype.getTarget=function(){return this.target};
b.prototype.setTarget=function(a){this.target=a};return b}();
Game.objects.Vehicle=function(){var d=Game.objects.Object.Static,b=function(a){d.call(this,a);this.setRotationFieldEnabled(!0);this.speed=0};classExtend(d,b);b.prototype.moveOnFrame=function(a,b){this.speed&&this.move(this.copySpeed().mul(b))};b.prototype.accelerateOnFrame=function(a,b){this.accel&&(this.speed+=this.accel*b)};b.prototype.getSpeed=function(){return 0===this.speed?Vec2.ZERO:new Vec2(Math.cos(this.radians)*this.speed,Math.sin(this.radians)*this.speed)};b.prototype.copySpeed=function(){return 0===
this.speed?new Vec2:this.getSpeed()};b.prototype.getAcceleration=function(){return 0===this.accel?Vec2.ZERO:new Vec2(Math.cos(this.radians)*this.accel,Math.sin(this.radians)*this.accel)};b.prototype.copyAcceleration=function(){return 0===this.accel?new Vec2:new Vec2(Math.cos(this.radians)*this.accel,Math.sin(this.radians)*this.accel)};b.prototype.accelerate=function(a){this.speed+=a};b.prototype.setSpeed=function(a){this.speed=a};b.prototype.setAcceleration=function(a){this.accel=a};return b}();Game.objects.particles=function(){var d={};d.Particle=function(){var b=Game.objects.Object,a=function(a,e,d){b.call(this);this.lifeTime=a;this.shape=e;this.color=d};classExtend(b,a);Game.objects.properties.LifeTime.applyOnClass(a);var e=override(a,"onFrame",function(a,b){e.call(this,a,b);this.isOutOfMap(a.getMap().getVisibleRect(),0,0)&&(this.lifeTime=0)});a.prototype.render=function(a){a.fillStyle=this.color;this.shape.draw(a,!0,!1)};a.prototype.getPosition=function(){return this.shape.center};a.prototype.copyPosition=
function(){return this.shape.center.clone()};a.prototype.rotate=function(a){this.shape.rotate(a)};a.prototype.grow=function(a){this.shape.grow(a)};a.prototype.canCollide=function(a){return!1};a.prototype.collides=function(a){return!1};a.prototype.getRenderLayer=function(){return Game.Map.LAYER_PARTCILES};var d=[-1];a.prototype.getCollisionLayers=function(){return d};a.prototype.prepareCollision=function(){console.stack("error : the method 'prepareCollision()' should not be called for a particle.")};
delete a.prototype.renderMouseOver;return a}();d.Stroked=function(){var b=d.Particle;StrokedParticle=function(a,e,d){b.call(this,a,e,d)};classExtend(b,StrokedParticle);StrokedParticle.prototype.render=function(a){a.strokeStyle=this.color;this.shape.draw(a,!1,!0)};return StrokedParticle}();d.Emitor=function(){var b=Game.objects.Object.Static,a=function(a,e){b.call(this);this.rate=a;this.emited=0;this.minLifeTime=.75;this.maxLifeTime=1.5;this.minAngle=0;this.maxAngle=2*Math.PI;this.minSpeed=300;this.maxSpeed=
400;this.speedDampFactor=2.5;this.reduceSizeFactor=1.2;this.emitDistance=0;e&&(this.max=e);this.particleGenerator=function(a,b,e,f){return new d.Particle(a,new Circle(b,5),"#"+Math.round(16777215*Math.random()).toString(16))};this.emitedParticles=[]};classExtend(b,a);a.prototype.restart=function(){this.emited=0};a.prototype.stop=function(){this.emited=-1};a.prototype.isRunning=function(){return 0<=this.emited};a.prototype.setAngles=function(a,b){this.setMinAngle(a);this.setMaxAngle(isNull(b)?a:b)};
a.prototype.setMinAngle=function(a){this.minAngle=a};a.prototype.setMaxAngle=function(a){this.maxAngle=a};a.prototype.getMinAngle=function(){return this.minAngle};a.prototype.getMaxAngle=function(){return this.maxAngle};a.prototype.setEmitDistance=function(a){this.emitDistance=a};a.prototype.getEmitDistance=function(){return this.emitDistance};a.prototype.setEmitRate=function(a){this.rate=a};a.prototype.getEmitRate=function(){return this.rate};a.prototype.setLifeTime=function(a,b){this.setMinLifeTime(a);
this.setMaxLifeTime(b?b>a?b:a:a)};a.prototype.setMinLifeTime=function(a){this.minLifeTime=a};a.prototype.setMaxLifeTime=function(a){this.maxLifeTime=a};a.prototype.getMinLifeTime=function(){return this.minLifeTime};a.prototype.getMaxLifeTime=function(){return this.maxLifeTime};a.prototype.setSpeedDampFactor=function(a){this.speedDampFactor=a};a.prototype.getSpeedDampFactor=function(){return this.speedDampFactor};a.prototype.setSizeReduceFactor=function(a){this.reduceSizeFactor=a};a.prototype.getSizeReduceFactor=
function(){return this.reduceSizeFactor};var e=override(a,"rotate",function(a){e.call(this,a);this.minAngle+=a;this.maxAngle+=a});a.prototype.getParticleGenerator=function(){return this.particleGenerator};a.prototype.setParticleGenerator=function(a){this.particleGenerator=a};var f=[-1];a.prototype.getCollisionLayers=function(){return f};a.prototype.getRenderLayer=function(){return Game.Map.LAYER_NONE};a.prototype.canCollide=function(a){return!1};var h=override(a,"onFrame",function(a,b){h.call(this,
a,b);var e=this.emitedParticles.length,d=Math.max(0,1-this.speedDampFactor*b),f=Math.max(0,1-this.reduceSizeFactor*b);if(0<e)for(;e--;)0>=this.emitedParticles[e].lifeTime?this.emitedParticles.splice(e,1):(this.emitedParticles[e].speed&&1!==d&&this.emitedParticles[e].speed.mul(d),1!==f&&this.emitedParticles[e].grow(f));this.max&&0===this.emitedParticles.length&&this.emited>=this.max&&this.kill(a);if(-1<this.emited&&(!this.max||this.emited<this.max)&&(d=this.emited+b*this.rate,this.max&&d>this.max&&
(d=this.max),e=Math.floor(d-Math.floor(this.emited)),this.emited=d,0<e))for(;e--;){var m=Math.random()*(this.maxLifeTime-this.minLifeTime)+this.minLifeTime,d=Math.round(Math.random()*(this.maxSpeed-this.minSpeed)+this.minSpeed);0<d?(f=Math.random()*(this.maxAngle-this.minAngle)+this.minAngle,m=this.particleGenerator(m,this.position,f,d),this.emitDistance&&m.move(Vec2.createFromRadians(f).mul(this.emitDistance)),m.speed=new Vec2(Math.cos(f)*d,Math.sin(f)*d)):m=this.particleGenerator(m,this.position,
0,0);this.emitedParticles.push(m);a.addObject(m)}if(this.particlePositionRelative&&this.speed&&!this.speed.isZero()&&(d=this.speed.clone().mul(b),e=this.emitedParticles.length,0<e))for(;e--;)this.emitedParticles[e].shape.move(d)});return a}();d.Explosion=function(){var b=d.Emitor,a=function(a){b.call(this,1E3*a,a);this.minLifeTime=.1;this.maxLifeTime=.5;this.minSpeed=500;this.maxSpeed=1500;this.speedDampFactor=2;this.reduceSizeFactor=3};classExtend(b,a);return a}();d.TraceDrawer=function(){TraceDrawer=
function(b,a){this.lifeTime=b;this.color=a};TraceDrawer.prototype.applyOnObject=function(b,a){var e=a.setPosition,d=this;a.setPosition=function(){var h,g;1==arguments.length?(h=arguments[0].x,g=arguments[0].y):(h=arguments[0],g=arguments[1]);var l=a.copyPosition();e.call(this,h,g);h=a.getPosition();if(!l.equals(h))d.onMove(b,l,h)}};TraceDrawer.applyOnClass=function(b){var a=b.prototype.moveOnFrame;b.prototype.moveOnFrame=function(b,d){if(this.traceDrawer){var h=this.copyPosition();a.call(this,b,d);
var g=this.getPosition();if(!h.equals(g))this.traceDrawer.onMove(b,h,g)}else a.call(this,b,d)}};TraceDrawer.prototype.onMove=function(b,a,e){a=this.getParticlesForTranslation(a,e);if(a.length)for(e=0;e<a.length;e++)b.addObject(a[e]);else b.addObject(a)};TraceDrawer.prototype.getParticlesForTranslation=function(b,a){return new d.Stroked(this.lifeTime,new Line(b,a),this.color)};return TraceDrawer}();return d}();Game.objects.bullets=function(){var d={},b=function(){var a=Game.objects.Object.Static,b=function(b,e,d,f){a.call(this,e);exists(d)&&(this.speed=d.clone());this.damages=b;isNull(f)||(this.lifeTime=f)};classExtend(a,b);Game.objects.particles.TraceDrawer.applyOnClass(b);Game.objects.properties.LifeTime.applyOnClass(b);b.defaultTraceDrawer=new TraceDrawer(.05,"#FF0000");b.defaultShape=new Polygon(Vec2.createVec2Array([-10,2,5,2,7,1,8,0,7,1,5,-2,-10,-2]));b.prototype.setLauncher=function(a){this.launcher=
a};b.prototype.getLauncher=function(){return this.launcher};b.prototype.getDamages=function(){return this.damages};b.prototype.setDamages=function(a){this.damages=a};b.prototype.onDeath=function(a){this.explosion&&(this.explosion.position.set(this.position),a.addObject(this.explosion))};var d=override(b,"moveOnFrame",function(a,b){d.call(this,a,b);this.isOutOfMap(a.gameMap.getVisibleRect())&&(delete this.explosion,this.kill(a))});b.COLLISION_LAYER=2;var h=[b.COLLISION_LAYER,Game.objects.Object.COLLISION_LAYER];
b.prototype.getCollisionLayers=function(){return h};b.prototype.onCollision=function(a,b){this.launcher!=b&&0!==this.damages&&(b.receiveDamages&&b.receiveDamages(a,this,this.damages)&&(this.damages=0),this.kill(a))};b.createBullet=function(a,d,f,h,g){a=new b(a,d,f);h=h.clone();h.rotate(f.getAngle());a.renderer=new GameObjectRenderer.Shaped(h.clone(),g);a.collider=new b.Collider(h);a.explosion=new ParticleEmitor.Explosion(20);a.traceDrawer=b.defaultTraceDrawer;return a};b.prototype.getRenderLayer=
function(){return Game.Map.LAYER_OBJ3};getInfo=override(b,"getInformations",function(){var a=getInfo.call(this);exists(this.lifeTime)&&a.push(["lifeTime : ",this.lifeTime].join(""));a.push(["damages : ",this.damages.toString()].join(""));return a});var g=override(b,"renderMouseOver",function(a,b,e,d){!e.running&&d&&g.call(this,a,b,e,d)});return b}();d.Bullet=b;d.Bullet.prototype=b.prototype;b=function(){var a=Game.objects.colliders.Shaped,b=function(b){a.call(this,b)};classExtend(a,b);b.prototype.collidesWhenInside=
function(a){return!0};return b}();d.Collider=b;d.Collider.prototype=b.prototype;b=function(){var a=d.Bullet,b=function(b,e,g,l,k){a.call(this,b,e,Vec2.ZERO,g);b=new Ray(e,k);this.renderer=new Game.objects.renderers.Shaped(b,l);this.collider=new d.Collider(b)};classExtend(a,b);return b}();d.Laser=b;d.Laser.prototype=b.prototype;b=function(){var a=d.Bullet,b=Game.objects.properties,f=function(b,e,d,f,h,g){a.call(this,b,e,d,g);this.maxSpeed=d.magnitude();this.steerForce=f;this.maxAngle=h;this.setRotationFieldEnabled(!0)};
classExtend(a,f);b.Homing.applyOnClass(f);f.prototype.getMaxSpeed=function(a){return this.maxSpeed*(1-Math.sqrt(this.maxSpeed/(150*a)))};f.prototype.getSteerForce=function(a,b){return a/Math.pow(b,1.2)*this.steerForce};var h=Game.objects.properties.Health.isDamageable,g=function(a,b){if(b.isInLayer(-1)||!h(b))return!1;for(var e=a.length,d=0;d<e;d++)if(b.isInLayer(a[d]))return!0;return!1};f.prototype.getTarget=function(a){var b,e=this.maxAngle,d=this.getPosition();a=a.getObjects(g.bind(void 0,this.getCollisionLayers()));
var f=a.length;if(0<f)for(;f--;)a[f]!==this.launcher&&(angle=(Vec2.translation(d,a[f].getPosition()).getAngle()-this.radians)%(2*Math.PI),angle>Math.PI&&(angle=2*Math.PI-angle),angle<e&&(e=angle,b=a[f]));return isNull(b)?null:b.getPosition()};var l=override(f,"onFrame",function(a,b){l.call(this,a,b);this.setRadians(this.getSpeed().getAngle())});return f}();d.Homing=b;d.Homing.prototype=b.prototype;return d}();Game.objects.interactives=function(){var d={};d.obstacles=function(){var b={};b.Obstacle=function(){var a=Game.objects.Object.Static,b=function(b){a.call(this,b)};classExtend(a,b);b.prototype.onCollision=function(a,b){};b.prototype.repulse=function(a,b){a.move(b);var d=a.copySpeed(),e=b.getAngle();d.rotate(-e);d.x=0;d.rotate(e);a.setSpeed(d)};b.COLLISION_LAYER=1;var d=[b.COLLISION_LAYER,Game.objects.Object.COLLISION_LAYER];b.prototype.getCollisionLayers=function(){return d};return b}();b.Rectangular=
function(){var a=b.Obstacle,d=function(b){a.call(this,b)};classExtend(a,d);d.prototype.disableBelow=function(a){this.enableBelowCross=a};d.prototype.disableAbove=function(a){this.enableAboveCross=a};d.prototype.disableLeft=function(a){this.enableLeftCross=a};d.prototype.disableRight=function(a){this.enableRightCross=a};d.prototype.onCollision=function(a,b){var d=this.getRadians(),e,k,n=b.getPosition();e=this.getPosition();var p=b.getSpeed();0!==d&&(this.getCollider().rotate(-d),b.getCollider().rotate(-d),
n=Vec2.translation(e,n).rotate(-d).add(e),p=p.clone().rotate(-d));e=b.getCollider().getRect(n);k=this.getCollider().getRect();var m=Vec2.zero();!this.enableAboveCross&&k.below(n)&&-.01<=p.y?m.y=k.top-e.bottom:!this.enableBelowCross&&k.above(n)&&.01>=p.y&&(m.y=k.bottom-e.top);!this.enableRightCross&&k.onLeftOf(n)&&.01>=p.x?m.x=k.right-e.left:!this.enableLeftCross&&k.onRightOf(n)&&-.01<=p.x&&(m.x=k.left-e.right);0!==d&&(this.getCollider().rotate(d),b.getCollider().rotate(d),m.rotate(d));m.isZero()||
this.repulse(b,m)};return d}();b.Circular=function(){var a=b.Obstacle,d=function(b){a.call(this,b)};classExtend(a,d);d.prototype.onCollision=function(a,b){var d=this.getPosition(),e=b.getPosition(),k=Vec2.translation(d,e),n=k.getAngle(),p=d.x+this.getCollider().getRadius(),m=b.getSpeed();0!==n&&(b.getCollider().rotate(-n),e=k.rotate(-n).add(d),m=m.clone().rotate(-n));0>=m.x?(d=b.getCollider().getRect(e),p=new Vec2(p-d.left,0),0!==n&&(b.getCollider().rotate(n),p.rotate(n)),p.isZero()||this.repulse(b,
p)):0!==n&&b.getCollider().rotate(n)};return d}();b.properties={Bumper:{applyOnObstacle:function(a,b){var d=a.repulse;a.repulse=function(a,b){var e=a.copySpeed();d.call(this,a,b);var k=b.getAngle();e.rotate(-k);e.x=-e.x*this.getBumperStrength();40<Math.abs(e.x)&&(e.rotate(k),a.setSpeed(e))};a.setBumperStrength=function(a){this.bumperStrength=a};a.getBumperStrength=function(){return this.bumperStrength};exists(b)&&a.setBumperStrength(b)},applyOnObstacleClass:function(a,b){var d=override(a,"repulse",
function(a,b){var e=a.copySpeed();d.call(this,a,b);var k=b.getAngle();e.rotate(-k);e.x=-e.x*this.getBumperStrength();40<Math.abs(e.x)&&(e.rotate(k),a.setSpeed(e))});a.prototype.setBumperStrength=function(a){this.bumperStrength=a};a.prototype.getBumperStrength=function(){return this.bumperStrength};exists(b)&&(a.prototype.bumperStrength=b)}}};return b}();return d}();Game.weapons=function(){var d={};d.Weapon=function(){var b=function(a,b){this.damages=a;isNull(b)||this.setOwner(b)};b.prototype.use=function(a,b,d){};b.prototype.setOwner=function(a){this.owner=a};b.prototype.getOwner=function(){return this.owner};b.prototype.getDamages=function(){return this.damages};b.prototype.setDamages=function(a){this.damages=a};b.prototype.onDeath=function(){delete this.damages;this.owner&&delete this.owner};b.applyOnClass=function(a){a.prototype.setWeapon=function(a){isNull(a)?
exists(this.weapon)&&delete this.weapon:this.weapon=a};a.prototype.getWeapon=function(){return this.weapon};a.prototype.useWeapon=function(a){isNull(this.weapon)||this.weapon.use(a,this.getPosition(),this.getRadians())};var b=override(a,"onDeath",function(a){exists(this.weapon)&&(this.weapon.onDeath(),delete this.weapon);b.call(this,a)})};b.applyOnObject=function(a){a.setWeapon=function(a){isNull(a)?exists(this.weapon)&&delete this.weapon:this.weapon=a};a.getWeapon=function(){return this.weapon};
a.useWeapon=function(a){exists(this.weapon)&&this.weapon.use(a,this.getPosition(),this.gertRadians())};var b=a.onDeath;a.onDeath=function(a){exists(this.weapon)&&(this.weapon.onDeath(),delete this.weapon);b.call(this,a)}};return b}();d.Gun=function(){var b=d.Weapon,a=function(a,d,e){b.call(this,a,e);this.bulletGenerator=d};classExtend(b,a);a.prototype.createBullet=function(a,b){var d=this.bulletGenerator(this.getDamages(),a,b),e=this.getOwner();e&&d.setLauncher(e);return d};a.prototype.use=function(a,
b,d){a.addObject(this.createBullet(b,d))};a.defaultBulletValues={renderShape:Game.objects.bullets.Bullet.defaultShape,colliderShape:Game.objects.bullets.Bullet.defaultShape,color:"#0F0",speed:300,spawnDistance:5,explosionSize:0};a.createBulletGenerator=function(b){var d=createProperties(a.defaultBulletValues,b);return function(a,b,e){var f=Vec2.createFromRadians(e).mul(d.speed);a=new Game.objects.bullets.Bullet(a,b,f,d.lifeTime);a.renderer=new Game.objects.renderers.Shaped(d.renderShape,d.color);
a.collider=new Game.objects.colliders.Shaped(d.colliderShape);e&&a.rotate(e);isNull(d.trace)||(a.traceDrawer=d.trace);isNull(d.explosionSize)||(a.explosion=new Game.objects.particles.Explosion(d.explosionSize));return a}};a.defaultHomingBulletValues=createProperties(a.defaultBulletValues);a.defaultHomingBulletValues.maxAngle=Math.PI/8;a.createHomingBulletGenerator=function(b){var d=createProperties(a.defaultHomingBulletValues,b);exists(d.steerForce)||(d.steerForce=Math.pow(d.speed,1.6)/(10/Math.log(1+
d.maxAngle)));return function(a,b,e){var f=Vec2.createFromRadians(e).mul(d.speed);a=new Game.objects.bullets.Homing(a,b,f,d.steerForce,d.maxAngle,d.lifeTime);a.renderer=new Game.objects.renderers.Shaped(d.renderShape,d.color);a.collider=new Game.objects.colliders.Shaped(d.colliderShape);e&&a.rotate(e);isNull(d.trace)||(a.traceDrawer=d.trace);isNull(d.explosionSize)||(a.explosion=new Game.objects.particles.Explosion(d.explosionSize));return a}};a.createLaserBulletGenerator=function(a,b,d){var e;e=
exists(d)?new Line(Vec2.ZERO,new Vec2(d,0)):new Ray(Vec2.ZERO,0);return function(b,h,p){isNull(d)||(h=Vec2.createFromRadians(p).mul(d/2).add(h));b=new Game.objects.bullets.Bullet(b,h,Vec2.ZERO,.01);b.renderer=new Game.objects.renderers.Shaped(e,a);b.renderer.fill=!1;b.renderer.stroke=!0;b.collider=new Game.objects.colliders.Shaped(e);b.rotate(p);return b}};var e=override(a,"onDeath",function(){e.call(this);delete this.bulletGenerator});return a}();return d}();Game.Physics=function(){var d={G:6.67384E-11,friction:2,Mass:{applyOnClass:function(b,a){b.prototype.mass=exists(a)?a:0;b.prototype.setMass=function(a){this.mass=a};b.prototype.getMass=function(){return this.mass};b.prototype.applyForce=function(a){a=(new Vec2(a)).mul(this.getMass());a.add(this.copyAcceleration());this.setAcceleration(a)}},applyOnObject:function(b,a){b.setMass=function(a){this.mass=a};b.getMass=function(){return this.mass};b.applyForce=function(a){a=(new Vec2(a)).mul(this.getMass());
a.add(this.copyAcceleration());this.setAcceleration(a)}},hasMass:function(b){return exists(b.getMass)},elasticCollision:function(b,a){var d=this.hasMass(b)?b.getMass():1,f=this.hasMass(a)?a.getMass():1,h=b.getPosition(),g=b.getSpeed(),l=a.getPosition(),k=a.getSpeed(),h=Vec2.translation(h,l).mul(Vec2.distance(g,k)/(d+f));b.setSpeed(h.clone().mul(f));a.setSpeed(h.mul(d))}},applyForce:function(b,a){b.setAcceleration(b.getAcceleration().add(a))},applyGravity:function(b,a){d.applyForce(b,a.clone().mul(9.81))},
applyFriction:function(b){var a=b.getSpeed();a&&!a.isZero()&&d.applyForce(b,a.clone().mul(friction))},applySpaceGravity:function(b,a){var e=a.mass|1,f=b.mass|1,h=Vec2.translation(b,a),e=d.G*e*f/h.squareMagnitude();d.applyForce(b,h.normalize().mul(e))}};return d}();Game.hud={};
Game.hud.Hud=function(){var d=function(b){this.views=[];this.currentView=null;b&&(this.context2d=b.getContext("2d"),b.style.background="#00000000");this.active=!0};d.prototype.addView=function(b){this.views.push(b)};d.prototype.removeView=function(b){b=this.views.indexOf(b);0<=b&&this.views.splice(b,1)};d.prototype.onRectUpdate=function(b){for(var a=0;a<view.length;a++)v.onRectUpdate(b)};d.prototype.updateRect=function(b){requestAnimationFrame(this.render.bind(this,this.context2d,b?b:new Rect(0,0,
this.context2d.canvas.width,this.context2d.canvas.height)))};d.prototype.getChildRect=function(b){return b.getRect()};d.prototype.getContext=function(){return this.context2d};d.prototype.render=function(b,a){for(var d=this.views.length,f=0;f<d;)this.views[f++].render(b,a)};d.prototype.mouseButton=function(b,a){return!isNull(this.currentView)&&this.currentView.onTouchEvent({position:position,description:a?Game.hud.views.EVENT_DESC.DOWN:Game.hud.views.EVENT_DESC.UP,button:b})};d.prototype.mouseMove=
function(b){if(this.active){var a,d,f={description:Game.hud.views.EVENT_DESC.MOVE,position:Vec2.zero()};if(this.currentView){if(this.currentView.hasFocus()&&(f.position.set(b).addXY(-a.left,-a.top),f.onTouchEvent(f)))return;this.currentView=null}var h=this.views.length,g;if(0<h)for(;h--;)if(d=this.views[h],!(d.state&Game.hud.views.STATE.INACTIVE)&&(a=d.getRect(),d==this.currentView||a.contains(b)))if(f.position.set(b).addXY(-a.left,-a.top),g||d==this.currentView&&!a.contains(b)||(g=d),d.onTouchEvent(f)){f.description=
Game.hud.views.EVENT_DESC.EXIT;if(this.currentView)this.currentView.onTouchEvent(f);this.currentView=d;break}!this.currentView&&g&&(this.currentView=g)}};d.prototype.click=function(b,a){return!isNull(this.currentView)&&this.currentView.onTouchEvent({position:b,description:Game.hud.views.EVENT_DESC.CLICK,button:a})};return d}();Game.hud.views={STATE:{INACTIVE:1,NONE:2,OVERED:4,PRESSED:8},EVENT_DESC:{MOVE:0,ENTER:1,EXIT:2,SCROLL:3,DOWN:4,UP:5,CLICK:6},TouchEvent:function(d,b,a,e){this.position=d;this.description=b;b==Game.hud.views.EVENT_DESC.SCROLL&&(this.scroll=a);b>=Game.hud.views.EVENT_DESC.DOWN&&(this.btn=a,this.pressed=e)}};
Game.hud.views.View=function(){var d=function(a){this.parentView=a};d.prototype.state=Game.hud.views.STATE.INACTIVE;d.prototype.render=function(a,b){};d.prototype.getState=function(){return this.state};d.prototype.setState=function(a){this.state=a};d.prototype.getParentView=function(){return this.parentView};d.prototype.setParentView=function(a){this.parentView=a};d.prototype.onRectUpdate=function(a){};d.prototype.getPosition=function(){return new Vec2(Vec2.ZERO)};d.prototype.containsPoint=function(a){return!1};
d.prototype.getRect=function(){return Rect.createFromPoint(this.getPosition())};d.prototype.onClick=function(a,b){console.log("onClick");return!1};var b=Game.hud.views.EVENT_DESC;d.prototype.onTouchEvent=function(a){console.log("touch event : "+a.description);switch(a.description){case b.DOWN:return this.state|=views.STATE.PRESSED,!0;case b.UP:return this.state&=views.STATE.OVERED,!1;case b.CLICK:return this.onClick(a.position,a.btn);case b.MOVE:return this.hasFocus();case b.ENTER:return this.state=
views.STATE.OVERED,this.hasFocus();case b.EXIT:return this.state=views.STATE.NONE,this.hasFocus()}};d.update=function(){var a=this.getParentView();isNull(a)||a.updateRect(a.getChildRect(this))};d.prototype.isOvered=function(){return 0!==(this.state&Game.hud.views.STATE.OVERED)};d.prototype.isPressed=function(){return 0!==(this.state&Game.hud.views.STATE.PRESSED)};d.prototype.hasFocus=function(){return this.isPressed()};d.prototype.toString=function(){return"hud.views.View"};return d}();
Game.hud.views.TextView=function(){var d=Game.hud.views.View,b=function(a,b,f,h){d.call(this,a);this.setText(b);isNull(f)||this.setRect(f);this.setFontSize(12);this.setFont("Verdana");isNull(h)||this.setTextColor(h)};classExtend(d,b);b.prototype.setText=function(a){this.text=a};b.prototype.getText=function(){return this.text};b.prototype.setFontSize=function(a){this.fontSize=a};b.prototype.getFontSize=function(){return this.fontSize};b.prototype.setFont=function(a){this.font=a};b.prototype.getFont=
function(){return this.font};b.prototype.setTextColor=function(a){this.textColor=a};b.prototype.getTextColor=function(){return this.textColor};b.prototype.setRect=function(){this.rect=rect};b.prototype.getRect=function(){return this.rect};b.prototype.getPosition=function(){return getRect().center()};b.prototype.containsPoint=function(a){return this.getRect().contains(a)};b.prototype.render=function(a,b){var d=this.getRect();isNull(d)&&(d=b);this.getState()&Game.hud.views.STATE.OVERED&&(a.lineWidth*=
2,a.strokeStyle="#fff",d.draw(a,this.fill,!0),a.lineWidth/=2);a.strokeStyle=this.getTextColor();var h=this.getFontSize();a.font=[h,"px ",this.getFont()].concat();a.wrapText(this.getText(),d,1.25*h,Gravity.CENTER,!1,!0)};return b}();
Game.hud.views.Button=function(){var d=Game.hud.views.TextView,b=function(a,b,h,g,l){isNull(l)&&(l="black");d.call(this,a,g,void 0,l);this.setShape(b);this.setShapeColor(h);this.stroke=!0;this.fill=!1;this.setGravity(Gravity.LEFT|Gravity.TOP)};classExtend(d,b);b.prototype.state=Game.hud.views.STATE.ACTIVE;b.prototype.setShape=function(a){this.shape=a.clone()};b.prototype.getShape=function(){return this.shape};b.prototype.getPosition=function(){return this.getShape().center};b.prototype.getRect=function(){return this.getShape().getRect()};
b.prototype.setGravity=function(a){this.gravity=a};b.prototype.getGravity=function(){return isNull(this.gravity)?Gravity.LEFT|Gravity.TOP:gravity};b.prototype.onClick=function(){return!0};b.prototype.getShapeColor=function(){return this.shapeColor};b.prototype.setShapeColor=function(a){this.shapeColor=a};b.prototype.setStroke=function(a){this.stroke=a};b.prototype.setFill=function(a){this.fill=a};b.prototype.containsPoint=function(a){return this.getShape().contains(a)};var a=override(b,"render",function(b,
d){b.fillStyle=b.strokeStyle=this.getShapeColor();this.getState()&Game.hud.views.STATE.OVERED?(b.lineWidth*=2,b.strokeStyle="#fff",this.getShape().draw(b,this.fill,!0),b.lineWidth/=2):this.getShape().draw(b,this.fill,this.stroke);a.call(this,b)});return b}();
Game.hud.views.ProgressBar=function(){var d=Game.hud.views.View,b=function(a,b,f,h,g){d.call(this,a);this.needFillUpdate=this.needStrokeUpdate=!0;this.setWidth(b);this.setHeight(f);this.setMax(h);this.setValue(g);this.setMargins(0,0);this.setGravity(Gravity.LEFT|Gravity.TOP);this.setColor("#f00")};classExtend(d,b);b.prototype.createShape=function(a,b){var d=a?this.getWidth():this.getWidth()/this.getMax()*this.getValue(),h=this.getHeight(),g=this.getGravity(),l=NaN,k=NaN,n=NaN,p=NaN;(g&Gravity.RIGHT)===
Gravity.RIGHT?p=b.right-this.getMarginX():l=(g&Gravity.LEFT)===Gravity.LEFT||(g&Gravity.CENTER)!==Gravity.CENTER?b.left+this.getMarginX():b.left+(canvasrect.width()-d)/2;(g&Gravity.BOTTTOM)===Gravity.BOTTOM?n=b.bottom-this.getMarginY():k=(g&Gravity.TOP)===Gravity.TOP||(g&Gravity.CENTER)!==Gravity.CENTER?b.top+this.getMarginY():b.top+(b.height()-h)/2;isNaN(l)?l=p-d:isNaN(p)&&(p=l+d);isNaN(k)?k=n-h:isNaN(n)&&(n=k+h);return(new Rect(l,k,p,n)).getShape()};b.prototype.setGravity=function(a){this.gravity=
a;this.needStrokeUpdate=this.needFillUpdate=!0};b.prototype.getGravity=function(){return this.gravity};b.prototype.getStrokeShape=function(a){this.needStrokeUpdate&&!isNull(a)&&(this.strokeShape=this.createShape(!0,a),this.needStrokeUpdate=!1);return this.strokeShape};b.prototype.getFillShape=function(a){this.needFillUpdate&&!isNull(a)&&(this.fillShape=this.createShape(!1,a),this.needFillUpdate=!1);return this.fillShape};b.prototype.setWidth=function(a){this.width=a;this.needStrokeUpdate=this.needFillUpdate=
!0};b.prototype.getWidth=function(){return this.width};b.prototype.setHeight=function(a){this.height=a;this.needStrokeUpdate=this.needFillUpdate=!0};b.prototype.getHeight=function(){return this.height};b.prototype.setMax=function(a){this.max=a;this.needFillUpdate=this.needStrokeUpdate=!0};b.prototype.getMax=function(){return this.max};b.prototype.setValue=function(a){this.value=a;this.needFillUpdate=!0};b.prototype.getValue=function(){return this.value};b.prototype.setMargins=function(a,b){typeof a==
TYPE_NUMBER&&(this.marginX=a);typeof b==TYPE_NUMBER&&(this.marginY=b);this.needStrokeUpdate=this.needFillUpdate=!0};b.prototype.getMarginX=function(){return this.marginX};b.prototype.getMarginY=function(){return this.marginY};b.prototype.setColor=function(a){this.color=a};b.prototype.getColor=function(){return this.color};b.prototype.onRectUpdate=function(a){this.needStrokeUpdate=this.needFillUpdate=!0};b.prototype.getPosition=function(){return this.getStrokeShape().center};b.prototype.getRect=function(){return this.getStrokeShape().getRect()};
b.prototype.containsPoint=function(a){var b=this.getStrokeShape();return!isNull(b)&&b.contains(a)};b.prototype.render=function(a,b){var d=this.getStrokeShape(b),h=this.getFillShape(b),g=this.getColor();a.fillStyle=g;h.draw(a,!0,!1);this.getState()&Game.hud.views.STATE.OVERED?(a.lineWidth*=2,a.strokeStyle="#fff",d.draw(a,!1,!0),a.lineWidth/=2):(a.strokeStyle=g,d.draw(a,!1,!0))};return b}();
Game.hud.views.SegmentedProgressBar=function(){var d=Game.hud.views.ProgressBar,b=function(a,b,f,h,g,l,k){d.call(this,a,b,f,h,g);this.setSegments(l);this.setInclination(k)};classExtend(d,b);b.prototype.setSegments=function(a){this.segments=a;this.needStrokeUpdate=this.needFillUpdate=!0};b.prototype.getSegments=function(){return this.segments};b.prototype.setInclination=function(a){this.inclination=a;this.needStrokeUpdate=this.needFillUpdate=!0};b.prototype.getInclination=function(){return this.inclination};
b.prototype.createShape=function(a,b){var d=this.getHeight(),h=this.getInclination(),g=this.getSegments(),l=this.getWidth()-h*d,k=l/g,n=d/g,p=n*h,d=[new Vec2(h*d,0),new Vec2(0,d)],m;if(a)for(h=1;h<g+1;h++)m=2*h,d.push(new Vec2(d[m-1].x+k,d[m-1].y)),d.push(new Vec2(d[m].x+p,d[m].y-n));else for(var q=this.getValue(),r=this.getMax(),h=1;h<g+1;h++)m=2*h,q>r*h/g?(d.push(new Vec2(d[m-1].x+k,d[m-1].y)),d.push(new Vec2(d[m].x+p,d[m].y-n))):(p=(q-r*(h-1)/g)*l/r,d.push(new Vec2(d[m-1].x+p,d[m-1].y)),d.push(new Vec2(d[0].x+
q/r*l,0)));g=new Polygon(d);g.moveXY(b.left+this.getMarginX(),b.top+this.getMarginY());l=this.getGravity();l&Gravity.BOTTOM&&g.mirrorVertically((b.top+b.bottom)/2);l&Gravity.RIGHT&&g.mirrorHorizontally((b.left+b.right)/2);return g};return b}();Game.hud.views.Layout=function(){var d=function(){this.children=[];this.currentView=null;this.rect=new Rect(0,0,Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER);this.setState(Game.hud.views.STATE.NONE)};d.prototype.addView=function(a,b){a.layoutParams=b;this.addView(a)};d.prototype.addView=function(a){a.layoutRule||(a.layoutParams=this.getDefaultLayoutParams());this.children.push(a)};d.prototype.getDefaultLayoutParams=function(){return{}};d.prototype.onTouchEvent=function(a){if(a.description<=Game.hud.views.EVENT_DESC.EXIT)return this.mouseMove(a);
if(!isNull(currentView))return currentView.onTouchEvent(a)};d.prototype.updateRect=function(a){this.getParentView().updateRect(a)};d.mouseMove=function(a){for(var b,d,h=!1,g=this.views.length,l=a.position;g--;)if(d=this.views[g],!(h&&d!=currentView||d.state&Game.hud.views.STATE.INACTIVE)){b=d.getRect();a.position.set(l).addXY(-b.left,-b.top);if(h&&d==currentView){currentView.onTouchEvent(a);break}if(d.onTouchEvent(a)){if(isNull(currentView)){currentView=d;break}h=!0;a.description=Game.hud.views.EVENT_DESC.EXIT}}};
var b=override(d,"render",function(a){b.call(this,a);a.save();a.translate(this.rect.left,this.rect.top);var d=this.getRect();a.rect(0,0,d.width(),d.height());a.clip();for(var d=this.children.length,f,h,g=0;g<d;g++)h=this.children[g],f=(new Vec2(this.getChildPosition(h))).remove(h.getPosition()),f.isZero()?h.render(a):(a.save(),a.translate(f.x,f.y),h.render(a),a.restore())});d.prototype.getIndexOf=function(a){return this.children.indexOf(a)};d.prototype.getChild=function(a){return this.children[a]};
d.prototype.getChildPosition=function(a){return typeof a!=TYPE_NUMBER?a.getPosition:this.getChildPosition(this.getChild(a))};d.prototype.getChildRect=function(a){return typeof a!=TYPE_NUMBER?a.getRect():this.getChild(a).getRect()};return d};
Game.hud.views.LinearLayout=function(){var d=function(b,a){this.horizontal=b;this.rtl=a};override(d,"getPosition",function(b){typeof b!=TYPE_NUMBER&&(b=this.getIndexOf(b));var a=this.getChild(b).getPosition().clone();0<b&&a.addXY(0,this.getChildRect(b-1).bottom);return a});override(d,"getRect",function(b){typeof b!=TYPE_NUMBER&&(b=this.getIndexOf(b));var a=getChildAt(b).getRect();0<b?(b=this.getChildRect(b-1),this.horizontal?a.moveXY(rtl?-b.left:b.right,0):a.moveXY(0,rtl?-b.top:b.bottom)):rtl&&(this.horizontal?
a.moveXY(this.getRect().width()-a.width(),0):a.moveXY(0,this.getRect().height()-a.height()));return a});return d}();